services:
  - type: web
    name: aupairconnect-backend
    env: node
    plan: free
    region: ohio
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false # O usuário precisará colar a URL do Neon/Supabase aqui
      - key: PORT
        value: 3001
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: REDIS_URL
        sync: false # (Opcional) se quiser usar Redis na nuvem
